---
title: "PPML"
author: "Author"
date: "2025-06-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fixest)
library(tidyverse)
library(dplyr)
```


```{r}
panel <- read.csv("../data/cleaned/panel_complete.csv",stringsAsFactors = FALSE)
```

```{r}
head(panel)
```

```{r}
9.936972 - 5.164386
#panel$dyad_id <- paste(panel$iso_o, panel$iso_d, sep = "_")
#write.csv(panel, "../data/cleaned/panel_complete.csv")
```

```{r}
panel$landlock_matched <- ifelse(panel$landlocked == 1 & panel$landlocked_d == 1, 1, 0)
```

```{r}
print(table(panel$landlock_matched))
```
```{r}
panel$dev <- ifelse(panel$development == 0 & panel$development_d == 0, 1, 
                    ifelse(panel$development == 1 & panel$development_d == 0, 2,
                           ifelse(panel$development == 0 & panel$development_d == 1, 3,
                                  ifelse(panel$development == 1 & panel$development_d == 1, 4,0))))
```

```{r}
print(table(panel$dev))
```
```{r}
panel$gdp_pct_sum <- panel$log_gdp_pct + panel$log_gdp_pct_d
```

```{r}
panel$gdp_pct_abs <- abs(panel$log_gdp_pct - panel$log_gdp_pct_d)
```

```{r}
# Non- cultural trade
residual_t <- resid(lm(as.numeric(panel$hysteresis_total) ~ as.numeric(panel$total_tr)))
panel$residual_t <- residual_t
```

```{r}
# reproducible cultural trade
residual_r <- resid(lm(as.numeric(panel$hysteresis_repro) ~ as.numeric(panel$reproducible_cultural_tr)))
panel$residual_r <- residual_r
# unique cultural trade
residual_u <- resid(lm(as.numeric(panel$hysteresis_unique) ~ as.numeric(panel$unique_cultural_tr)))
panel$residual_u <- residual_u
```



# Unique
```{r}
u_panel = fepois(unique_cultural_tr ~ gdp_pct_sum + gdp_pct_abs + rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
```

```{r}
summary(u_panel, cluster = list(panel$dyad_id))
```

```{r}
u_panel2 = fepois(unique_cultural_tr ~ gdp_pct_sum + gdp_pct_abs + hysteresis_unique + rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
summary(u_panel2, cluster = list(panel$dyad_id))
```




# Reproducible
```{r}
r_panel = fepois(reproducible_cultural_tr ~ gdp_pct_sum + gdp_pct_abs + rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
summary(r_panel, cluster = list(panel$dyad_id))
```

```{r}
r_panel2 = fepois(reproducible_cultural_tr ~ gdp_pct_sum + gdp_pct_abs + hysteresis_repro + rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
summary(r_panel2, cluster = list(panel$dyad_id))
```



# Non-cultural goods

```{r}
t_panel = fepois(total_tr ~ gdp_pct_sum + gdp_pct_abs + rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
summary(t_panel, cluster = list(panel$dyad_id))
```

```{r}
t_panel2 = fepois(total_tr ~ gdp_pct_sum + gdp_pct_abs + hysteresis_total +rta + contig + comlang_off + colony + comcol+ log_dist + landlock_matched + as.factor(dev) | TIME_PERIOD, panel)
summary(t_panel2, cluster = list(panel$dyad_id))
```





```{r}
# 
# coefplot(u_panel,
#          coefficients = c("hysteresis_unique", "log_gdp_pct", "log_gdp_pct_d", "log_dist", "contig", "comlang_off", "colony", "landlocked", "landlocked_d", "development", "development_d"),
#          decreasing = TRUE,
#          main = "Gravity Model Coefficients",
#          xlab = "Coefficient Value",
#          ylab = "Variables",
#          col = "blue",
#          ci.col = "red",
#          ylim = c(-1, 2))
```

